#!/usr/bin/env bash
# Deploy after GitHub Actions has rsync'd the tree into APP_DIR.
# Prefer the repo copy of this script (auto-updated by rsync). ~/bin may be a bootstrap.
set -euo pipefail

APP_DIR="${APP_DIR:-$HOME/apps/devsecops-skills-suite}"
REPO_DEPLOY="${APP_DIR}/deploy/server/gha-deploy.sh"
BOOTSTRAP_MARKER="${APP_DIR}/.deploy-bootstrap-done"

# If SSH forced-command still points at ~/bin/gha-deploy.sh, re-exec the
# rsynced script so deploy logic always matches the code just synced.
if [[ -f "$REPO_DEPLOY" && "${INFRALENS_DEPLOY_REEXEC:-}" != "1" ]]; then
  if ! cmp -s "$REPO_DEPLOY" "$0" 2>/dev/null; then
    export INFRALENS_DEPLOY_REEXEC=1
    exec bash "$REPO_DEPLOY" "$@"
  fi
fi

COMPOSE_PROFILE="${COMPOSE_PROFILE:-container-app}"
REQUIRE_N8N="${REQUIRE_N8N:-true}"

cd "$APP_DIR"

if [[ ! -f .env ]]; then
  echo "ERROR: missing $APP_DIR/.env (required for deploy)" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

ensure_env_default() {
  local key="$1"
  local val="$2"
  if grep -q "^${key}=" .env 2>/dev/null; then
    return 0
  fi
  echo "${key}=${val}" >> .env
  export "${key}=${val}"
  echo "==> Appended ${key} to .env"
}

ensure_n8n_encryption_key() {
  local current="${N8N_ENCRYPTION_KEY:-}"
  if [[ -n "$current" && "$current" != "infralens-onprem-n8n-change-me" ]]; then
    return 0
  fi
  local key
  if command -v openssl >/dev/null 2>&1; then
    key="$(openssl rand -hex 24)"
  else
    key="$(head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  if grep -q '^N8N_ENCRYPTION_KEY=' .env 2>/dev/null; then
    sed -i "s|^N8N_ENCRYPTION_KEY=.*|N8N_ENCRYPTION_KEY=${key}|" .env
  else
    {
      echo ""
      echo "# Auto-generated by gha-deploy.sh ($(date -u +%Y-%m-%dT%H:%MZ))"
      echo "N8N_ENCRYPTION_KEY=${key}"
    } >> .env
  fi
  export N8N_ENCRYPTION_KEY="${key}"
  echo "==> Set N8N_ENCRYPTION_KEY in .env"
}

# Keep ~/bin in sync with the tree so forced-command stays current.
if [[ -f "$REPO_DEPLOY" ]]; then
  install -m 755 "$REPO_DEPLOY" "$HOME/bin/gha-deploy.sh" 2>/dev/null || true
  if [[ -f "${APP_DIR}/deploy/server/gha-ssh-wrapper.sh" ]]; then
    install -m 755 "${APP_DIR}/deploy/server/gha-ssh-wrapper.sh" "$HOME/bin/gha-ssh-wrapper.sh" 2>/dev/null || true
  fi
fi

PROFILE_ARGS=(--profile "$COMPOSE_PROFILE")

if [[ "$REQUIRE_N8N" == "true" ]]; then
  ensure_n8n_encryption_key
  ensure_env_default N8N_WEBHOOKS_ENABLED true
  ensure_env_default N8N_WEBHOOK_URL http://n8n:5678/webhook/infralens
fi

echo "==> Validating compose (profiles: ${PROFILE_ARGS[*]})"
docker compose "${PROFILE_ARGS[@]}" config >/dev/null

if [[ "$REQUIRE_N8N" == "true" ]]; then
  if ! docker compose "${PROFILE_ARGS[@]}" config --services | grep -qx "n8n"; then
    echo "ERROR: n8n service missing — on-prem n8n is mandatory" >&2
    exit 1
  fi
fi

echo "==> Building and restarting stack (profile=${COMPOSE_PROFILE})"
docker compose "${PROFILE_ARGS[@]}" up -d --build --remove-orphans

echo "==> Health check (API)"
API_PORT="${API_HOST_PORT:-8000}"
api_ok=0
for _ in $(seq 1 45); do
  if curl -fsS -m 3 "http://127.0.0.1:${API_PORT}/api/health" >/dev/null 2>&1; then
    curl -fsS -m 3 "http://127.0.0.1:${API_PORT}/api/health"
    echo
    api_ok=1
    break
  fi
  sleep 2
done
if [[ "$api_ok" != "1" ]]; then
  echo "ERROR: API health check failed after deploy" >&2
  docker compose "${PROFILE_ARGS[@]}" ps >&2 || true
  exit 1
fi

if [[ "$REQUIRE_N8N" == "true" ]]; then
  echo "==> Health check (n8n)"
  N8N_PORT="${N8N_HOST_PORT:-5678}"
  n8n_ok=0
  for _ in $(seq 1 45); do
    if curl -fsS -m 3 "http://127.0.0.1:${N8N_PORT}/healthz" >/dev/null 2>&1; then
      echo "n8n healthy on :${N8N_PORT}"
      n8n_ok=1
      break
    fi
    sleep 2
  done
  if [[ "$n8n_ok" != "1" ]]; then
    echo "ERROR: n8n health check failed after deploy (on-prem n8n is mandatory)" >&2
    docker compose "${PROFILE_ARGS[@]}" ps >&2 || true
    docker compose "${PROFILE_ARGS[@]}" logs --tail=80 n8n >&2 || true
    exit 1
  fi
fi

touch "$BOOTSTRAP_MARKER" 2>/dev/null || true
echo "==> Deploy OK"
exit 0
