"""Delivery orchestration: isolate workspace → GitHub PR → gated plan/apply."""
from __future__ import annotations

import re
from typing import Any

from app.core.azure_client import AzureOpenAINotConfiguredError
from app.core.db import DeliveryRun, SessionLocal, _now
from app.core.rbac import has_min_role
from app.platform.engineering import iac_repair, iac_workspace
from app.providers import github_git


def _run(run_id: str) -> dict[str, Any]:
    with SessionLocal() as session:
        row = session.get(DeliveryRun, run_id)
        if row is None:
            raise LookupError("Delivery run not found")
        if row.status not in {"active", "completed"}:
            raise ValueError("Delivery run is not active")
        return {
            "id": row.id,
            "project_id": row.project_id,
            "artifacts": dict(row.artifacts or {}),
        }


def _patch(run_id: str, updates: dict[str, Any]) -> dict[str, Any]:
    from app.platform import delivery

    with SessionLocal() as session:
        row = session.get(DeliveryRun, run_id)
        if row is None:
            raise LookupError("Delivery run not found")
        artifacts = dict(row.artifacts or {})
        artifacts.update(updates)
        row.artifacts = artifacts
        row.updated_at = _now()
        session.commit()
    loaded = delivery.get_run(run_id)
    if loaded is None:
        raise LookupError("Delivery run not found")
    return loaded


def _output(result: dict[str, Any]) -> str:
    return ((result.get("stderr") or "") + "\n" + (result.get("stdout") or "")).strip()


_ALREADY_EXISTS = re.compile(
    r'resource with the ID "(?P<id>/subscriptions/[^"]+)" already exists.*?'
    r"\n\s*with (?P<addr>[A-Za-z0-9_./\[\]-]+),",
    re.IGNORECASE | re.DOTALL,
)


def parse_already_exists(error: str) -> list[tuple[str, str]]:
    seen: set[str] = set()
    found: list[tuple[str, str]] = []
    for match in _ALREADY_EXISTS.finditer(error or ""):
        address = match.group("addr")
        resource_id = match.group("id")
        if address in seen:
            continue
        seen.add(address)
        found.append((address, resource_id))
    return found


def _import_existing(project_id: str, run_id: str, error: str) -> list[str]:
    imported: list[str] = []
    for address, resource_id in parse_already_exists(error):
        data_addr = address if address.startswith("data.") else f"data.{address}"
        iac_workspace.run_state_rm(project_id, run_id, data_addr)
        result = iac_workspace.run_import(project_id, run_id, address, resource_id)
        if result.get("returncode") == 0:
            imported.append(address)
    return imported


def _progress(run_id: str, repair: dict[str, Any], text: str, *, phase: str, status: str = "running") -> None:
    _patch(
        run_id,
        {
            "terraform_progress": text,
            "terraform_repair": {
                **repair,
                "status": status,
                "phase": phase,
                "progress": text,
            },
        },
    )


def sync_workspace(run_id: str) -> dict[str, Any]:
    row = _run(run_id)
    synced = iac_workspace.sync(row["project_id"], row["id"])
    return _patch(run_id, {"iac_workspace": synced})


def push_github(run_id: str, *, username: str = "") -> dict[str, Any]:
    row = _run(run_id)
    synced = iac_workspace.sync(row["project_id"], row["id"])
    files = iac_workspace.load_generated_files(row["project_id"], row["id"])
    branch = f"infralens/iac/{row['project_id'][:8]}/{row['id'][:8]}"
    pushed = github_git.push_files_pr(
        row["project_id"],
        files,
        branch=branch,
        title=f"infra: InfraLens IaC for {row['project_id']}",
        body=(
            f"Isolated Terraform generated by InfraLens delivery `{row['id']}`.\n"
            f"Files live under `{github_git.repo_prefix(row['project_id'])}/` "
            "and do not replace application source.\n"
            f"Requested by {username or 'unknown'}."
        ),
    )
    return _patch(
        run_id,
        {
            "iac_workspace": synced,
            "terraform_pr": {
                "status": "opened" if pushed.get("pr_url") else "pushed",
                "title": f"infra: InfraLens IaC for {row['project_id']}",
                "files": pushed.get("files") or [],
                "silent_apply": False,
                "repo": pushed.get("repo"),
                "branch": pushed.get("branch"),
                "pr_url": pushed.get("pr_url"),
                "commit": pushed.get("commit"),
                "message": "Pushed to the project-mapped repository with this project's GitHub token.",
            },
            "github_push": pushed,
        },
    )


def _run_init_once(project_id: str, run_id: str) -> dict[str, Any]:
    synced = iac_workspace.sync(project_id, run_id)
    init = iac_workspace.run_phase(project_id, run_id, "init")
    ok = init.get("returncode") in {0, None}
    return {
        "ok": ok,
        "phase": "init",
        "error": "" if ok else iac_repair.redact(_output(init))[:2000],
        "synced": synced,
        "terraform_init": {
            "status": "passed" if ok else "failed",
            "returncode": init.get("returncode"),
            "stdout": iac_repair.redact(init.get("stdout") or "")[:4000],
            "stderr": iac_repair.redact(init.get("stderr") or "")[:4000],
            "workspace": synced.get("workspace"),
        },
    }


def _run_plan_once(project_id: str, run_id: str) -> dict[str, Any]:
    synced = iac_workspace.sync(project_id, run_id)
    init = iac_workspace.run_phase(project_id, run_id, "init")
    if init.get("returncode") not in {0, None}:
        return {
            "ok": False,
            "phase": "init",
            "error": iac_repair.redact(_output(init))[:2000],
            "synced": synced,
            "terraform_init": {
                "status": "failed",
                "returncode": init.get("returncode"),
                "stdout": iac_repair.redact(init.get("stdout") or "")[:4000],
                "stderr": iac_repair.redact(init.get("stderr") or "")[:4000],
                "workspace": synced.get("workspace"),
            },
        }
    validate = iac_workspace.run_phase(project_id, run_id, "validate")
    if validate.get("returncode") not in {0, None}:
        return {
            "ok": False,
            "phase": "validate",
            "error": iac_repair.redact(_output(validate))[:2000],
            "synced": synced,
            "terraform_init": {
                "status": "passed",
                "returncode": 0,
                "workspace": synced.get("workspace"),
            },
        }
    plan = iac_workspace.run_phase(project_id, run_id, "plan")
    summary = plan.get("plan_summary") or {}
    ok = plan.get("returncode") in {0, 2}
    error = "" if ok else iac_repair.redact(_output(plan))[:2000]
    return {
        "ok": ok,
        "phase": "plan",
        "error": error,
        "synced": synced,
        "terraform_init": {
            "status": "passed",
            "returncode": 0,
            "workspace": synced.get("workspace"),
        },
        "action_diff": {
            "plan_summary": (
                f"Plan: {summary.get('add')} add, {summary.get('change')} change, "
                f"{summary.get('destroy')} destroy"
                if summary.get("add") is not None
                else (error or iac_repair.redact((plan.get("stdout") or plan.get("stderr") or ""))[:1200])
            ),
            "blast_radius": plan.get("blast_radius") or "medium",
            "rollback": "Do not apply. Workspace state is local to this project run.",
            "expected_result": "Plan matches the architecture model without deleting unrelated prod data",
            "preflight": "isolated workspace + project Azure/AWS credentials only",
            "status": "passed" if ok else "failed",
            "add": summary.get("add"),
            "change": summary.get("change"),
            "destroy": summary.get("destroy"),
            "workspace": synced.get("workspace"),
        },
    }


def _run_apply_once(project_id: str, run_id: str, *, refresh: bool) -> dict[str, Any]:
    if refresh:
        iac_workspace.drop_plan_file(project_id, run_id)
        planned = _run_plan_once(project_id, run_id)
        if not planned.get("ok"):
            return planned
    else:
        iac_workspace.sync(project_id, run_id)
        planned = {}
    applied = iac_workspace.run_phase(project_id, run_id, "apply", auto_approve=True)
    ok = applied.get("returncode") == 0
    return {
        "ok": ok,
        "phase": "apply",
        "timed_out": bool(applied.get("timed_out")),
        "error": "" if ok else iac_repair.redact(_output(applied))[:2000],
        "synced": planned.get("synced") or {"workspace": applied.get("workspace")},
        "action_diff": planned.get("action_diff"),
        "apply_result": {
            "status": "applied" if ok else "failed",
            "gated": True,
            "isolated": True,
            "workspace": applied.get("workspace"),
            "returncode": applied.get("returncode"),
            "stdout": iac_repair.redact(applied.get("stdout") or "")[:4000],
            "stderr": iac_repair.redact(applied.get("stderr") or "")[:2000],
            "message": (
                "Applied with this project's cloud credentials in an isolated workspace."
                if ok
                else "Apply failed. Azure OpenAI will try to repair Terraform if this is a config error."
            ),
        },
    }


def _run_destroy_once(project_id: str, run_id: str) -> dict[str, Any]:
    synced = iac_workspace.sync(project_id, run_id)
    destroyed = iac_workspace.run_phase(project_id, run_id, "destroy", auto_approve=True)
    ok = destroyed.get("returncode") == 0
    return {
        "ok": ok,
        "phase": "destroy",
        "timed_out": bool(destroyed.get("timed_out")),
        "error": "" if ok else iac_repair.redact(_output(destroyed))[:2000],
        "synced": synced,
        "revert_result": {
            "status": "reverted" if ok else "failed",
            "gated": True,
            "isolated": True,
            "workspace": destroyed.get("workspace") or synced.get("workspace"),
            "returncode": destroyed.get("returncode"),
            "stdout": iac_repair.redact(destroyed.get("stdout") or "")[:4000],
            "stderr": iac_repair.redact(destroyed.get("stderr") or "")[:2000],
            "message": (
                "Destroyed isolated workspace resources with this project's cloud credentials."
                if ok
                else "Revert failed. Azure OpenAI will try to repair Terraform if destroy is blocked by config."
            ),
        },
    }


def _repair_once(
    run_id: str,
    *,
    project_id: str,
    phase: str,
    attempt: int,
    error: str,
    repair: dict[str, Any],
) -> dict[str, Any]:
    row = _run(run_id)
    artifacts = dict(row.get("artifacts") or {})
    def _stop(diagnosis: str, files: list[str]) -> dict[str, Any]:
        turns = iac_repair.record_turn(
            list(repair.get("turns") or []),
            phase=phase,
            attempt=attempt,
            error=error,
            diagnosis=diagnosis,
            files=files,
        )
        repair.update({"turns": turns, "last_diagnosis": diagnosis})
        return {"ok": False, "stop": True, "diagnosis": diagnosis, "files": files, "repair": repair}

    try:
        proposal = iac_repair.propose_fix(
            phase=phase,
            error=error,
            files=iac_workspace.load_generated_files(project_id, run_id),
            architecture=iac_repair.slim_architecture(artifacts),
            turns=list(repair.get("turns") or []),
        )
    except AzureOpenAINotConfiguredError as exc:
        return _stop(str(exc), [])
    except Exception as exc:  # noqa: BLE001
        return _stop(f"Azure OpenAI repair failed: {exc}", [])

    if proposal.get("unfixable"):
        return _stop(str(proposal.get("diagnosis") or "Azure OpenAI marked this error unfixable"), [])
    changed = iac_repair.apply_file_updates(project_id, run_id, proposal.get("files") or {})
    if changed:
        iac_workspace.drop_plan_file(project_id, run_id)
    if not changed:
        return _stop(str(proposal.get("diagnosis") or "No file changes proposed"), [])
    turns = iac_repair.record_turn(
        list(repair.get("turns") or []),
        phase=phase,
        attempt=attempt,
        error=error,
        diagnosis=str(proposal.get("diagnosis") or ""),
        files=changed,
    )
    repair.update({"turns": turns, "last_diagnosis": proposal.get("diagnosis") or ""})
    return {
        "ok": True,
        "stop": False,
        "diagnosis": proposal.get("diagnosis") or "",
        "files": changed,
        "repair": repair,
    }


def _with_repair(run_id: str, phase: str, *, refresh_apply: bool = False) -> dict[str, Any]:
    row = _run(run_id)
    project_id = row["project_id"]
    repair = iac_repair.existing_context(row.get("artifacts"))
    _progress(run_id, repair, f"Starting terraform {phase}", phase=phase)

    try:
        return _with_repair_attempts(
            run_id,
            phase,
            project_id=project_id,
            repair=repair,
            refresh_apply=refresh_apply,
        )
    except (LookupError, ValueError, PermissionError, RuntimeError):
        raise
    except Exception as exc:  # noqa: BLE001
        last_error = f"terraform {phase} crashed: {exc}"
        _progress(run_id, repair, last_error[:400], phase=phase, status="failed")
        updates: dict[str, Any] = {
            "terraform_repair": {
                **repair,
                "status": "failed",
                "phase": phase,
                "progress": last_error[:400],
            },
            "terraform_progress": last_error[:400],
        }
        if phase == "apply":
            updates["apply_result"] = {
                "status": "failed",
                "gated": True,
                "isolated": True,
                "message": last_error[:800],
            }
        if phase == "destroy":
            updates["revert_result"] = {
                "status": "failed",
                "gated": True,
                "isolated": True,
                "message": last_error[:800],
            }
        return _patch(run_id, updates)


def _with_repair_attempts(
    run_id: str,
    phase: str,
    *,
    project_id: str,
    repair: dict[str, Any],
    refresh_apply: bool,
) -> dict[str, Any]:
    row = _run(run_id)
    last_error = ""
    last_outcome: dict[str, Any] = {}
    for attempt in range(1, iac_repair.MAX_ATTEMPTS + 1):
        _progress(run_id, repair, f"Running terraform {phase} (attempt {attempt}/{iac_repair.MAX_ATTEMPTS})", phase=phase)
        if phase == "init":
            outcome = _run_init_once(project_id, run_id)
        elif phase == "plan":
            outcome = _run_plan_once(project_id, run_id)
        elif phase == "destroy":
            outcome = _run_destroy_once(project_id, run_id)
        else:
            outcome = _run_apply_once(project_id, run_id, refresh=refresh_apply or attempt > 1)
        last_outcome = outcome
        if outcome.get("ok"):
            repair = {
                **repair,
                "status": "passed",
                "phase": phase,
                "progress": f"{phase} passed after {attempt} attempt(s)",
            }
            updates: dict[str, Any] = {
                "iac_workspace": outcome.get("synced") or {},
                "terraform_repair": repair,
                "terraform_progress": repair["progress"],
            }
            if outcome.get("terraform_init"):
                updates["terraform_init"] = outcome["terraform_init"]
                if phase == "init":
                    prev = dict((row.get("artifacts") or {}).get("action_diff") or {})
                    if prev:
                        updates["action_diff"] = {
                            **prev,
                            "status": "stale",
                            "plan_summary": "Init completed. Re-run isolated plan before apply.",
                        }
            if outcome.get("action_diff"):
                updates["action_diff"] = outcome["action_diff"]
            if outcome.get("apply_result"):
                updates["apply_result"] = outcome["apply_result"]
            if outcome.get("revert_result"):
                updates["revert_result"] = outcome["revert_result"]
                if outcome["revert_result"].get("status") == "reverted":
                    prev_apply = dict((row.get("artifacts") or {}).get("apply_result") or {})
                    updates["apply_result"] = {
                        **prev_apply,
                        "status": "reverted",
                        "message": outcome["revert_result"].get("message")
                        or "Isolated stack reverted with terraform destroy.",
                    }
                    prev_plan = dict((row.get("artifacts") or {}).get("action_diff") or {})
                    if prev_plan:
                        updates["action_diff"] = {
                            **prev_plan,
                            "status": "stale",
                            "plan_summary": "Stack reverted. Re-run isolated plan before apply.",
                        }
            return _patch(run_id, updates)

        last_error = str(outcome.get("error") or f"terraform {outcome.get('phase') or phase} failed")
        if outcome.get("timed_out"):
            _progress(
                run_id,
                repair,
                f"{phase} timed out (attempt {attempt}/{iac_repair.MAX_ATTEMPTS}); retrying without file changes",
                phase=phase,
            )
            continue
        imported = _import_existing(project_id, run_id, last_error) if phase != "destroy" else []
        if imported:
            iac_workspace.drop_plan_file(project_id, run_id)
            _progress(
                run_id,
                repair,
                f"Imported existing Azure resource(s) {', '.join(imported)}; retrying {phase}",
                phase=phase,
            )
            continue
        _progress(
            run_id,
            repair,
            f"Azure OpenAI repairing {outcome.get('phase') or phase} (attempt {attempt}/{iac_repair.MAX_ATTEMPTS})",
            phase=phase,
        )
        fixed = _repair_once(
            run_id,
            project_id=project_id,
            phase=str(outcome.get("phase") or phase),
            attempt=attempt,
            error=last_error,
            repair=repair,
        )
        repair = dict(fixed.get("repair") or repair)
        _progress(run_id, repair, str(fixed.get("diagnosis") or last_error)[:400], phase=phase)
        if fixed.get("stop"):
            break

    repair = {
        **repair,
        "status": "failed",
        "phase": phase,
        "progress": last_error[:400] or f"{phase} failed",
    }
    updates = {
        "terraform_repair": repair,
        "terraform_progress": repair["progress"],
        "iac_workspace": last_outcome.get("synced") or {},
    }
    if last_outcome.get("terraform_init"):
        updates["terraform_init"] = last_outcome["terraform_init"]
    if last_outcome.get("action_diff"):
        updates["action_diff"] = last_outcome["action_diff"]
    elif phase == "plan":
        updates["action_diff"] = {
            "plan_summary": last_error[:1200],
            "status": "failed",
            "phase": last_outcome.get("phase") or phase,
        }
    if last_outcome.get("apply_result"):
        failed_apply = dict(last_outcome["apply_result"])
        failed_apply["message"] = last_error[:800] or failed_apply.get("message")
        updates["apply_result"] = failed_apply
    if last_outcome.get("revert_result"):
        failed_revert = dict(last_outcome["revert_result"])
        failed_revert["message"] = last_error[:800] or failed_revert.get("message")
        updates["revert_result"] = failed_revert
    elif phase == "init":
        updates["terraform_init"] = last_outcome.get("terraform_init") or {
            "status": "failed",
            "stderr": last_error[:2000],
        }
    return _patch(run_id, updates)


def run_init(run_id: str) -> dict[str, Any]:
    return _with_repair(run_id, "init")


def run_plan(run_id: str) -> dict[str, Any]:
    row = _run(run_id)
    init = dict((row.get("artifacts") or {}).get("terraform_init") or {})
    if init.get("status") != "passed":
        raise ValueError("Run terraform init first. Use Init so Azure OpenAI can fix init errors before plan.")
    return _with_repair(run_id, "plan")


def run_apply(run_id: str, *, user_role: str, confirm_destroy: bool = False) -> dict[str, Any]:
    if not has_min_role(user_role, "devops_lead"):
        raise PermissionError("Terraform apply requires DevOps Lead or above")
    row = _run(run_id)
    plan = dict((row.get("artifacts") or {}).get("action_diff") or {})
    if plan.get("status") != "passed":
        raise ValueError("Run a successful terraform plan in this isolated workspace before apply")
    destroy = int(plan.get("destroy") or 0)
    if destroy > 0 and not confirm_destroy:
        raise ValueError(
            f"Plan would destroy {destroy} resource(s). Re-submit with confirm_destroy=true."
        )
    return _with_repair(run_id, "apply")


def run_destroy(run_id: str, *, confirm: bool = False) -> dict[str, Any]:
    row = _run(run_id)
    apply = dict((row.get("artifacts") or {}).get("apply_result") or {})
    if apply.get("status") not in {"applied", "failed", "reverted", "reverting"}:
        raise ValueError("Nothing to revert. Apply isolated infrastructure first.")
    if not confirm:
        raise ValueError("Re-submit with confirm=true to destroy the isolated stack.")
    return _with_repair(run_id, "destroy")
